import os

CURRENT_WORKING_DIRECTORY = os.getcwd()
DATABASE_NAME = 'sales_management.db'
DATABASE_PATH = os.path.join(CURRENT_WORKING_DIRECTORY, 'database', DATABASE_NAME)
LOGGING_NAME = 'app.log'
LOGGING_PATH = os.path.join(CURRENT_WORKING_DIRECTORY, LOGGING_NAME)
MAT_HANG_TABLE = 'MatHang'
BAN_HANG_TABLE = 'BanHang'
NHAP_HANG_TABLE = 'NhapHang'
KHACH_HANG_TABLE = 'KhachHang'
NCC_TABLE = 'NCC'
CHI_PHI_TABLE = 'ChiPhi'
DON_VI_TABLE = 'DonVi'

# ---- generate_id ----
MAT_HANG_ID_LENGTH = 6
MAT_HANG_ID_PREFIX = 'MH'

BAN_HANG_ID_LENGTH = 10
BAN_HANG_ID_PREFIX = 'BH'

NHAP_HANG_ID_LENGTH = 8
NHAP_HANG_ID_PREFIX = 'NH'

KHACH_HANG_ID_LENGTH = 6
KHACH_HANG_ID_PREFIX = 'KH'

NCC_ID_LENGTH = 6
NCC_ID_PREFIX = 'NCC'

CHI_PHI_ID_LENGTH = 10
CHI_PHI_ID_PREFIX = 'CP'


# --- CSS ---
FAMILY_FONT = 'Arial'

# --- Color ---
BG_COLOR_LIGHT_BLUE = 'lightblue'
BG_COLOR_RED = 'red'
BG_COLOR_GREEN = 'green'
BG_COLOR_BLUE = 'blue'
BG_COLOR_YELLOW = 'yellow'
BG_COLOR_WHITE = 'white'
BG_COLOR_BLACK = 'black'
BG_COLOR_GRAY = 'gray'
BG_COLORLIGHT_GRAY = 'lightgray'
BG_COLOR_ORANGE = 'orange'

TEXT_COLOR = 'black'
TEXT_COLOR_RED = 'red'
TEXT_COLOR_GREEN = 'green'
TEXT_COLOR_BLUE = 'blue'
TEXT_COLOR_YELLOW = 'yellow'
TEXT_COLOR_WHITE = 'white'
TEXT_COLOR_LIGHT_BLUE = 'lightblue'
TEXT_COLOR_ORANGE = 'orange'

WARP_LENGTH = 300
BUTTON_WARP_LENGTH = 300
BUTTON_BD = 3
BUTTON_HEIGHT = 3
BUTTON_WIDTH = 30
BUTTON_PADX = 5
BUTTON_PADY = 5
BUTTON_RELIEF = 'raised'
BUTTON_CURSOR = 'hand2'





