# Generated by Django 5.0.6 on 2024-07-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loudspeaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loudspeaker',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
