# Generated by Django 5.0.6 on 2024-07-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('category', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('view', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('time_total', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.producer')),
            ],
            options={
                'verbose_name_plural': 'audio_books',
            },
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('url', models.TextField()),
                ('file_type', models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav'), ('ogg', 'ogg')], default='mp3', max_length=4)),
                ('description', models.TextField()),
                ('time', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audiobook.audiobook')),
            ],
            options={
                'verbose_name_plural': 'book_sections',
            },
        ),
    ]
