# Generated by Django 5.0.7 on 2024-08-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='category',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
        migrations.AlterField(
            model_name='booksection',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
