# Generated by Django 4.0.1 on 2024-06-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DoctorModel.address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DoctorModel.level'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DoctorModel.name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='place_of_work',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DoctorModel.placework'),
        ),
    ]
