# Generated by Django 5.0.6 on 2024-07-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryStick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('view', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=255, null=True)),
                ('price_old', models.IntegerField(default=0)),
                ('price_new', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('memory', models.CharField(choices=[('1', '1GB'), ('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB'), ('256', '256GB'), ('512', '512GB'), ('1024', '1024GB')], default='16', max_length=10)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.producer')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='type.type')),
            ],
            options={
                'verbose_name_plural': 'MemorySticks',
            },
        ),
    ]
