# Generated by Django 5.0.6 on 2024-07-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('sayings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saying',
            name='category',
        ),
        migrations.AddField(
            model_name='saying',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
