# Generated by Django 5.0.6 on 2024-07-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayings', '0002_remove_saying_category_saying_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saying',
            old_name='category',
            new_name='categories',
        ),
    ]
