# Generated by Django 5.0.6 on 2024-07-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
